### ISSUE TITLE
not work for blender 4.2.3

### ISSUE THREAD

**Issue by tao1261060556** [AIGODLIKE/ComfyUI-BlenderAI-node#137]
now it is not work for blender 4.2.3

**Comment by GeminiSquishGames** [comment]
It helps to be more specific, so if you can provide more details on what exactly isn't working compared to how it worked for you before, that may help AIGODLIKE or even others since the code is available to us. I've never gotten it to work but would seriously like to have it in my workflow.

Though, I'm not sure the project is still living or simply not well maintained at this point. Haven't heard anything from them.

**Comment by Yorha4D** [comment]
@tao1261060556 @GeminiSquishGames Hi, it can run on Blender 3.6-4.3 versions. Please check if your ComfyUI is configured correctly and avoid using custom nodes with low-quality code.

https://github.com/user-attachments/assets/a109b05e-10b2-42b5-b339-0770915eb6e6
