### ISSUE TITLE
Trouble seeing the workspace and addon interface

### ISSUE THREAD

**Issue by nodegraphics** [AIGODLIKE/ComfyUI-BlenderAI-node#34]
Hello,
Im using Blender 3.6.2 - after installing the addon i couldn't see the interface for comfyUI. 
I was wondering if i missed a step or maybe im using unsupported version of blender. 
I would appreciate your help,

<img width="460" alt="Screenshot - 2023-10-17 19 42 07" src="https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/10071439/648d7cc1-3952-416d-9ad8-7673e9477f38">

<img width="346" alt="Screenshot - 2023-10-17 19 43 51" src="https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/10071439/5ac37b6b-d846-4561-89ad-97a2b4356dd5">

<img width="556" alt="Screenshot 2023-10-17 194222" src="https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/10071439/1c7eb82c-9a7f-4a4c-a1e0-81a3c38c9e42">

Thank you

**Comment by KarryCharon** [comment]
@gnlkrmz Is there any error message printed on console? Or you can try the develop branch which is the newest addon.

**Comment by gnlkrmz** [comment]
@KarryCharon no i dont have any error printed on console. I can try develop branch....can you let me know where to get that ?

**Comment by KarryCharon** [comment]
@gnlkrmz try this command `git clone https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node -b develop`

**Comment by gnlkrmz** [comment]
@KarryCharon Thanks. Looks like it doesn wanna work with my version :) maybe im doing something wrong but seems like i cant see any workspace or addon UI.
thank you.

**Comment by KarryCharon** [comment]
@gnlkrmz can you show me the console info? Just open your system console by this button:
<img width="882" alt="image" src="https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/49889381/a4428d60-9f3f-49dc-a586-710d2ab0223d">

If addon runs correctly, it will look like this:
<img width="1366" alt="image" src="https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/49889381/0f9f8eaf-97d2-4858-a4d9-579562b03112">

**Comment by gnlkrmz** [comment]
@KarryCharon of course. 
attached the log
https://drive.google.com/file/d/1nr9K63rWxOiRCcPkVIRZ-27MmIjQvS-Y/view?usp=sharing

**Comment by KarryCharon** [comment]
@gnlkrmz some non-standard enums caused socket type register error. may fix the next commit, you can try the basic comfyui portable for testing

**Comment by gnlkrmz** [comment]
@KarryCharon sounds good. thank you. i will try it with a separate version

**Comment by KarryCharon** [comment]
@gnlkrmz Bug fixed. Try and enjoy it! :)

**Comment by gnlkrmz** [comment]
I just donwloaded and tried but no luck :( Im including log if it helps. 

`Read prefs: "C:\Users\gonul\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
blenderkit addon: Verbose is enabled
blenderkit addon: Read in JSON settings from file
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\gonul\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons\\addon\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\gonul\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons\\version.py'
[397236, 462672]
Drag & Drop Window Opened
module changed on disk: 'C:\\Program Files\\Blender Foundation\\Blender 3.6\\3.6\\scripts\\addons\\object_print3d_utils\\__init__.py' reloading...
Imported greeble and plating files
Registering Plasticity client
Plasticity client registered
Imported shape_generator
[SDN-INF]: UnregNode Time: 0.00s
[SDN-INF]: Launch Time: 0.00s
[SDN-WAR]: Parsing Node Start
[SDN-WAR]: Non-Standard Enum Detected: LoraLoader|pysssss[lora_name] -> [{'content': 'add_detail.safetensors', 'image': 'loras/add_detail.png'}, {'content': 'Aether_Bubbles_And_Foam_v1_SDXL_LoRA.safetensors', 'image': 'loras/Aether_Bubbles_And_Foam_v1_SDXL_LoRA.png'}, {'content': 'Aether_Cloud_v1.safetensors', 'image': 'loras/Aether_Cloud_v1.png'}, {'content': 'Aether_Ghost_v1.1_LoRA.safetensors', 'image': 'loras/Aether_Ghost_v1.1_LoRA.png'}, {'content': 'Afrofuturist_Fashion.safetensors', 'image': 'loras/Afrofuturist_Fashion.png'}, {'content': 'age_slider_v20.safetensors', 'image': 'loras/age_slider_v20.png'}, {'content': 'akirabikev0.2.safetensors', 'image': 'loras/akirabikev0.2.png'}, {'content': 'AnalogRedmondV2-Analog-AnalogRedmAF.safetensors', 'image': 'loras/AnalogRedmondV2-Analog-AnalogRedmAF.png'}, {'content': 'Chromatic_Taleweaver.safetensors', 'image': 'loras/Chromatic_Taleweaver.png'}, {'content': 'ClassipeintXL1.9.safetensors', 'image': 'loras/ClassipeintXL1.9.png'}, {'content': 'Clay Animation.safetensors', 'image': 'loras/Clay Animation.png'}, {'content': 'ClothingAdjuster3.safetensors', 'image': 'loras/ClothingAdjuster3.png'}, {'content': 'collageXL1.0.safetensors', 'image': 'loras/collageXL1.0.png'}, {'content': 'Colorwater_v4.safetensors', 'image': 'loras/Colorwater_v4.png'}, {'content': 'detail_slider_v4.safetensors', 'image': 'loras/detail_slider_v4.png'}, {'content': 'detailed_eye-10.safetensors', 'image': 'loras/detailed_eye-10.png'}, {'content': 'dis_V1-000020.safetensors', 'image': 'loras/dis_V1-000020.png'}, {'content': 'epi_noiseoffset2.safetensors', 'image': 'loras/epi_noiseoffset2.png'}, {'content': 'epiCRealismHelper.safetensors', 'image': 'loras/epiCRealismHelper.png'}, {'content': 'flashlightphoto_v1.5a.safetensors', 'image': 'loras/flashlightphoto_v1.5a.png'}, {'content': 'fu3g0.safetensors', 'image': 'loras/fu3g0.png'}, {'content': 'Graphic_Portrait.safetensors', 'image': 'loras/Graphic_Portrait.png'}, {'content': 'Graphic_XL_v1.5.safetensors', 'image': 'loras/Graphic_XL_v1.5.png'}, {'content': 'GrayClay_V1.5.5.safetensors', 'image': 'loras/GrayClay_V1.5.5.png'}, {'content': 'Lancia Stratos Zero (1970).safetensors', 'image': 'loras/Lancia Stratos Zero (1970).png'}, {'content': 'Lines_clothes_SD15.safetensors', 'image': 'loras/Lines_clothes_SD15.png'}, {'content': 'Lines_Clothes_XL.safetensors', 'image': 'loras/Lines_Clothes_XL.png'}, {'content': 'LowRA.safetensors', 'image': 'loras/LowRA.png'}, {'content': 'Lunatic_Portrait.safetensors', 'image': 'loras/Lunatic_Portrait.png'}, {'content': 'mangaboxstyle.safetensors', 'image': 'loras/mangaboxstyle.png'}, {'content': 'miniature_V1.safetensors', 'image': 'loras/miniature_V1.png'}, {'content': 'NASE.safetensors', 'image': 'loras/NASE.png'}, {'content': 'onoff4.safetensors', 'image': 'loras/onoff4.png'}, {'content': 'onoffunder1.safetensors', 'image': 'loras/onoffunder1.png'}, {'content': 'pixel-art-xl-v1.1.safetensors', 'image': 'loras/pixel-art-xl-v1.1.png'}, {'content': 'PoliceBodycamFootage.safetensors', 'image': 'loras/PoliceBodycamFootage.png'}, {'content': 'polyhedron_skinny_all.pt', 'image': 'loras/polyhedron_skinny_all.png'}, {'content': 'Retro-UI-XL-000009.safetensors', 'image': 'loras/Retro-UI-XL-000009.png'}, {'content': 'Retro_Magazine.safetensors', 'image': 'loras/Retro_Magazine.png'}, {'content': 'rppc-final.safetensors', 'image': 'loras/rppc-final.png'}, {'content': 'sd_xl_offset_example-lora_1.0.safetensors', 'image': 'loras/sd_xl_offset_example-lora_1.0.png'}, {'content': 'SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 'image': 'loras/SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.png'}, {'content': 'sdxl_illustration.safetensors', 'image': 'loras/sdxl_illustration.png'}, {'content': 'sdxl_pixel.safetensors', 'image': 'loras/sdxl_pixel.png'}, {'content': 'SDXL_Sewing_dol_v2.safetensors', 'image': 'loras/SDXL_Sewing_dol_v2.png'}, {'content': 'TapeGag-v1.safetensors', 'image': 'loras/TapeGag-v1.png'}, {'content': 'users_LORA_619530869304060153_ad.safetensors', 'image': 'loras/users_LORA_619530869304060153_ad.png'}, {'content': 'users_LORA_619530869304060153_dark.safetensors', 'image': 'loras/users_LORA_619530869304060153_dark.png'}, {'content': 'users_LORA_619530869304060153_Geometric composition.safetensors', 'image': 'loras/users_LORA_619530869304060153_Geometric composition.png'}, {'content': 'users_LORA_619530869304060153_laydown.safetensors', 'image': 'loras/users_LORA_619530869304060153_laydown.png'}, {'content': 'users_LORA_619530869304060153_old money.safetensors', 'image': 'loras/users_LORA_619530869304060153_old money.png'}, {'content': 'users_LORA_625253535268793777_FlashPhoto-v1.0.safetensors', 'image': 'loras/users_LORA_625253535268793777_FlashPhoto-v1.0.png'}, {'content': 'users_LORA_627831331690192459_art_deco_fusion-10.safetensors', 'image': 'loras/users_LORA_627831331690192459_art_deco_fusion-10.png'}, {'content': 'users_LORA_627831331690192459_cd_music.safetensors', 'image': 'loras/users_LORA_627831331690192459_cd_music.png'}, {'content': 'users_LORA_627831331690192459_Color_Fashion_sdxl.safetensors', 'image': 'loras/users_LORA_627831331690192459_Color_Fashion_sdxl.png'}, {'content': 'users_LORA_627831331690192459_Cyber_ID_sdxl.safetensors', 'image': 'loras/users_LORA_627831331690192459_Cyber_ID_sdxl.png'}, {'content': 'users_LORA_627831331690192459_dec_doc-15.safetensors', 'image': 'loras/users_LORA_627831331690192459_dec_doc-15.png'}, {'content': 'users_LORA_627831331690192459_digital_human.safetensors', 'image': 'loras/users_LORA_627831331690192459_digital_human.png'}, {'content': 'users_LORA_627831331690192459_Echoes_sdxl.safetensors', 'image': 'loras/users_LORA_627831331690192459_Echoes_sdxl.png'}, {'content': 'users_LORA_627831331690192459_Harmonious_Dreamer-10.safetensors', 'image': 'loras/users_LORA_627831331690192459_Harmonious_Dreamer-10.png'}, {'content': 'users_LORA_627831331690192459_Headset.safetensors', 'image': 'loras/users_LORA_627831331690192459_Headset.png'}, {'content': 'users_LORA_627831331690192459_minimalist_sci-fi_dystopia-10.safetensors', 'image': 'loras/users_LORA_627831331690192459_minimalist_sci-fi_dystopia-10.png'}, {'content': 'users_LORA_627831331690192459_Pencil_Sketch_Style.safetensors', 'image': 'loras/users_LORA_627831331690192459_Pencil_Sketch_Style.png'}, {'content': 'users_LORA_627831331690192459_skeleton_toy_sdxl.safetensors', 'image': 'loras/users_LORA_627831331690192459_skeleton_toy_sdxl.png'}, {'content': 'users_LORA_627831331690192459_Travel_Photography_SD15.safetensors', 'image': 'loras/users_LORA_627831331690192459_Travel_Photography_SD15.png'}, {'content': 'users_LORA_627831331690192459_VeloFusion_Skyriders_scifi_veicle.safetensors', 'image': 'loras/users_LORA_627831331690192459_VeloFusion_Skyriders_scifi_veicle.png'}, {'content': 'users_LORA_627831331690192459_yearbooks_photo-10.safetensors', 'image': 'loras/users_LORA_627831331690192459_yearbooks_photo-10.png'}, {'content': 'weight_slider_v2.safetensors', 'image': 'loras/weight_slider_v2.png'}, {'content': 'xl_more_art-full_v1.safetensors', 'image': 'loras/xl_more_art-full_v1.png'}, {'content': 'XrayFilm-000008.safetensors', 'image': 'loras/XrayFilm-000008.png'}, {'content': 'yhmotorbikev.safetensors', 'image': 'loras/yhmotorbikev.png'}, {'content': 'zyd232_InkStyle_v1_0.safetensors', 'image': 'loras/zyd232_InkStyle_v1_0.png'}, {'content': 'zynp_BaseSD1.5_lora_v1.0-000001.safetensors', 'image': None}, {'content': 'zynp_BaseSD1.5_lora_v1.0-000002.safetensors', 'image': None}, {'content': 'zynp_BaseSD1.5_lora_v1.0-000003.safetensors', 'image': None}, {'content': 'zynp_BaseSD1.5_lora_v1.0-000004.safetensors', 'image': None}, {'content': 'zynp_BaseSD1.5_lora_v1.0-000005.safetensors', 'image': None}, {'content': 'zynp_BaseSD1.5_lora_v1.0-000006.safetensors', 'image': None}, {'content': 'zynp_BaseSD1.5_lora_v1.0-000007.safetensors', 'image': None}, {'content': 'zynp_BaseSD1.5_lora_v1.0-000008.safetensors', 'image': None}, {'content': 'zynp_BaseSD1.5_lora_v1.0-000009.safetensors', 'image': None}]
[SDN-WAR]: Non-Standard Enum Detected: CheckpointLoader|pysssss[ckpt_name] -> [{'content': '7Of9ScenicEdition_v3ScenicEdition.safetensors', 'image': 'checkpoints/7Of9ScenicEdition_v3ScenicEdition.png'}, {'content': 'absolutereality_v181.safetensors', 'image': 'checkpoints/absolutereality_v181.png'}, {'content': 'Amigo 1.2 XL.safetensors', 'image': 'checkpoints/Amigo 1.2 XL.png'}, {'content': 'analogMadness_v60.safetensors', 'image': 'checkpoints/analogMadness_v60.png'}, {'content': 'aniverse_thxEd14Pruned.safetensors', 'image': 'checkpoints/aniverse_thxEd14Pruned.png'}, {'content': 'architectureExterior_v40Exterior.safetensors', 'image': 'checkpoints/architectureExterior_v40Exterior.png'}, {'content': 'artUniverse_v80.safetensors', 'image': 'checkpoints/artUniverse_v80.png'}, {'content': 'aZovyaRPGArtistTools_v3.safetensors', 'image': 'checkpoints/aZovyaRPGArtistTools_v3.png'}, {'content': 'boomerArtModelBAM_bam.safetensors', 'image': 'checkpoints/boomerArtModelBAM_bam.png'}, {'content': 'cineDiffusion_v3.safetensors', 'image': 'checkpoints/cineDiffusion_v3.png'}, {'content': 'classicAnim-v1.ckpt', 'image': 'checkpoints/classicAnim-v1.png'}, {'content': 'collageDiffusion_v10Ckpt.ckpt', 'image': 'checkpoints/collageDiffusion_v10Ckpt.png'}, {'content': 'CounterfeitV30_v30.safetensors', 'image': 'checkpoints/CounterfeitV30_v30.png'}, {'content': 'counterfeitxl_v10.safetensors', 'image': 'checkpoints/counterfeitxl_v10.png'}, {'content': 'crystalClear_Photorealistic.safetensors', 'image': 'checkpoints/crystalClear_Photorealistic.png'}, {'content': 'cyberrealistic_v33.safetensors', 'image': 'checkpoints/cyberrealistic_v33.png'}, {'content': 'darkSushiMixMix_colorful.safetensors', 'image': 'checkpoints/darkSushiMixMix_colorful.png'}, {'content': 'deliberate_v3.safetensors', 'image': 'checkpoints/deliberate_v3.png'}, {'content': 'disneyPixarCartoon_v10.safetensors', 'image': 'checkpoints/disneyPixarCartoon_v10.png'}, {'content': 'disneyPixarCartoonTypeA_10.safetensors', 'image': 'checkpoints/disneyPixarCartoonTypeA_10.png'}, {'content': 'doomerBoomer_v10.safetensors', 'image': 'checkpoints/doomerBoomer_v10.png'}, {'content': 'Double_Exposure_v2.safetensors', 'image': 'checkpoints/Double_Exposure_v2.png'}, {'content': 'doubleExposurePhoto_doubleExposurePhoto.safetensors', 'image': 'checkpoints/doubleExposurePhoto_doubleExposurePhoto.png'}, {'content': 'dreamshaperXL10_alpha2Xl10.safetensors', 'image': 'checkpoints/dreamshaperXL10_alpha2Xl10.png'}, {'content': 'dynavisionXLAllInOneStylized_release0534bakedvae.safetensors', 'image': 'checkpoints/dynavisionXLAllInOneStylized_release0534bakedvae.png'}, {'content': 'elegantEntropy_v13.safetensors', 'image': 'checkpoints/elegantEntropy_v13.png'}, {'content': 'epicphotogasm_x.safetensors', 'image': 'checkpoints/epicphotogasm_x.png'}, {'content': 'epicrealism_naturalSinRC1VAE.safetensors', 'image': 'checkpoints/epicrealism_naturalSinRC1VAE.png'}, {'content': 'epicrealism_pureEvolutionV3.safetensors', 'image': 'checkpoints/epicrealism_pureEvolutionV3.png'}, {'content': 'fennPhoto_v10.safetensors', 'image': 'checkpoints/fennPhoto_v10.png'}, {'content': 'fenrisxl_145.safetensors', 'image': 'checkpoints/fenrisxl_145.png'}, {'content': 'helloyoung25d_V10f.safetensors', 'image': None}, {'content': 'helloyoung2d_V10h.safetensors', 'image': None}, {'content': 'humans_v10.safetensors', 'image': 'checkpoints/humans_v10.png'}, {'content': 'juggernaut_aftermath.safetensors', 'image': 'checkpoints/juggernaut_aftermath.png'}, {'content': 'juggernautXL_version5.safetensors', 'image': 'checkpoints/juggernautXL_version5.png'}, {'content': 'LCM_Dreamshaper_v7_4k.safetensors', 'image': 'checkpoints/LCM_Dreamshaper_v7_4k.png'}, {'content': 'lomostyle_v10.safetensors', 'image': 'checkpoints/lomostyle_v10.png'}, {'content': 'lomoxl_.safetensors', 'image': 'checkpoints/lomoxl_.png'}, {'content': 'mdjrny-v4.safetensors', 'image': 'checkpoints/mdjrny-v4.png'}, {'content': 'neverendingDreamNED_v122BakedVae.safetensors', 'image': 'checkpoints/neverendingDreamNED_v122BakedVae.png'}, {'content': 'nextphoto_v30.safetensors', 'image': 'checkpoints/nextphoto_v30.png'}, {'content': 'nightvisionXLPhotorealisticPortrait_v0743ReleaseBakedvae.safetensors', 'image': 'checkpoints/nightvisionXLPhotorealisticPortrait_v0743ReleaseBakedvae.png'}, {'content': 'photon_v1.safetensors', 'image': 'checkpoints/photon_v1.png'}, {'content': 'prometheus.safetensors', 'image': 'checkpoints/prometheus.png'}, {'content': 'protovisionXLHighFidelity3D_release0620Bakedvae.safetensors', 'image': 'checkpoints/protovisionXLHighFidelity3D_release0620Bakedvae.png'}, {'content': 'raynaenvisionxl_10.safetensors', 'image': 'checkpoints/raynaenvisionxl_10.png'}, {'content': 'rcnzCartoon3d_v20.safetensors', 'image': 'checkpoints/rcnzCartoon3d_v20.png'}, {'content': 'RealCartoonXLV4.safetensors', 'image': 'checkpoints/RealCartoonXLV4.png'}, {'content': 'realisticStockPhoto_v10.safetensors', 'image': 'checkpoints/realisticStockPhoto_v10.png'}, {'content': 'realisticVisionV51_v51VAE.safetensors', 'image': 'checkpoints/realisticVisionV51_v51VAE.png'}, {'content': 'realvisxlV20_v20Bakedvae.safetensors', 'image': 'checkpoints/realvisxlV20_v20Bakedvae.png'}, {'content': 'reliberate_v20.safetensors', 'image': 'checkpoints/reliberate_v20.png'}, {'content': 'revAnimated_v122EOL.safetensors', 'image': 'checkpoints/revAnimated_v122EOL.png'}, {'content': 'sd_xl_base_1.0_0.9vae.safetensors', 'image': 'checkpoints/sd_xl_base_1.0_0.9vae.png'}, {'content': 'sd_xl_refiner_1.0_0.9vae.safetensors', 'image': 'checkpoints/sd_xl_refiner_1.0_0.9vae.png'}, {'content': 'sdvn6Realxl_detailface.safetensors', 'image': 'checkpoints/sdvn6Realxl_detailface.png'}, {'content': 'sdXL_v10VAEFix.safetensors', 'image': None}, {'content': 'sdxlHK_v075.safetensors', 'image': 'checkpoints/sdxlHK_v075.png'}, {'content': 'sdxlNijiSpecial_sdxlNijiSE.safetensors', 'image': 'checkpoints/sdxlNijiSpecial_sdxlNijiSE.png'}, {'content': 'toonyou_beta6.safetensors', 'image': 'checkpoints/toonyou_beta6.png'}, {'content': 'v1-5-pruned.ckpt', 'image': 'checkpoints/v1-5-pruned.png'}, {'content': 'v1-5-pruned.safetensors', 'image': 'checkpoints/v1-5-pruned.png'}]
[SDN-WAR]: Non-Standard Enum Detected: ttN pipeEncodeConcat[toggle] -> [True, False]
[SDN-WAR]: Non-Standard Enum Detected: ttN pipeLoraStack[toggle] -> [True, False]
[SDN-WAR]: Non-Standard Enum Detected: ttN textDebug[print_to_console] -> [False, True]
[SDN-WAR]: Non-Standard Enum Detected: ttN hiresfixScale[rescale_after_model] -> [False, True]
[SDN-WAR]: Non-Standard Enum Detected: ttN hiresfixScale[output_latent] -> [False, True]
Exception in module register(): C:\Users\gonul\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\gonul\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\__init__.py", line 47, in register
    TaskManager.run_server(fake=True)
  File "C:\Users\gonul\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\SDNode\manager.py", line 902, in run_server
    rtnode_reg()
  File "C:\Users\gonul\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\SDNode\tree.py", line 743, in rtnode_reg
    nt_desc, node_clss, socket_clss = NodeParser().parse()
  File "C:\Users\gonul\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\SDNode\nodes.py", line 826, in parse
    node_clss = self._parse_node_clss()
  File "C:\Users\gonul\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\SDNode\nodes.py", line 929, in _parse_node_clss
    nodes_desc = self._get_n_desc()
  File "C:\Users\gonul\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\SDNode\nodes.py", line 844, in _get_n_desc
    desc["output"][index][1] = out_name
IndexError: list index out of range
blenderkit updater: Running background check for update
blenderkit addon: Starting background checking thread
blenderkit addon: Checking for update now in background
blenderkit addon: Checking for update function
blenderkit INFO: Global dir permissions are OK. [22:30:11.666, utils.py:1296]
blenderkit addon: Read in JSON settings from file
blenderkit addon: Determined it's not yet time to check for updates
blenderkit addon: Aborting check for updated, check interval not reached
blenderkit addon: Finished check update, doing callback
blenderkit addon: Running background update callback
blenderkit addon: BG thread: Finished check update, no callback
blenderkit INFO: Dependencies are available [22:30:11.733, dependencies.py:111]
blenderkit WARNING: Request for daemon reports failed: <class 'requests.exceptions.ConnectTimeout'> HTTPConnectionPool(host='127.0.0.1', port=62485): Max retries exceeded with url: /report (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021620560820>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.1)')) [22:30:12.055, timer.py:36]
blenderkit INFO: Daemon server starting on address http://127.0.0.1:62485, log file for errors located at: C:\Users\gonul\Documents\cg.lib\blender.lib\lib\addons\_addon.data\blenderkit.data\daemon\daemon-62485.log [22:30:12.068, daemon_lib.py:605]
blenderkit WARNING: Request for daemon reports failed: <class 'requests.exceptions.ConnectTimeout'> HTTPConnectionPool(host='127.0.0.1', port=62485): Max retries exceeded with url: /report (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000021620561030>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.1)')) [22:30:12.212, timer.py:36]
blenderkit WARNING: Request for daemon reports failed: <class 'requests.exceptions.ConnectTimeout'> HTTPConnectionPool(host='127.0.0.1', port=62485): Max retries exceeded with url: /report (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000216205617B0>, 'Connection to 127.0.0.1 timed out. (connect timeout=0.1)')) [22:30:12.431, timer.py:36]
blenderkit INFO: Daemon is running on port 62485! [22:30:12.645, timer.py:86]
`

**Comment by KarryCharon** [comment]
@gnlkrmz maybe some cached json file is needed,  you can find it at  `C:\Users\gonul\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ComfyUI-BlenderAI-node-develop\SDNode\object_info.json`
This file is the node description, so that we can parse the all of the node.
Can you commit your json file?
Thank a lot !

**Comment by gnlkrmz** [comment]
[object_info.json](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/files/13111284/object_info.json)
here is the file

**Comment by KarryCharon** [comment]
@gnlkrmz fixed again! :)

**Comment by nodegraphics** [comment]
@KarryCharon Thank you !!! it works !!

**Comment by KarryCharon** [comment]
@nodegraphics u r welcome
